version: '2'

services:
  mosquitto:
    image: eclipse-mosquitto:1.6.9
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./01-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./01-mosquitto/users:/mosquitto/config/users
      - ${DATA_DIR}/mosquitto/data:/mosquitto/data
      - ${DATA_DIR}/mosquitto/log:/mosquitto/log
    restart: always

  influxdb:
    image: influxdb:1.8.0
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ${DATA_DIR}/influxdb:/var/lib/influxdb
    restart: always

  grafana:
    image: grafana/grafana:7.0.0
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - ${DATA_DIR}/grafana:/var/lib/grafana
    restart: always

  mqttbridge:
    build: ./02-bridge
    image: nilhcem/mqttbridge
    container_name: mqttbridge
    depends_on:
      - mosquitto
      - influxdb
    restart: always

  temtop-bridge:
    build: ./temtop-elitech-cloud-bridge
    image: jwright/temtop-elitech-cloud-bridge
    container_name: temtop-bridge
    depends_on:
      - influxdb
    restart: always
    environment:
      TEMPTOP_USER: "${TEMPTOP_USER}"
      TEMPTOP_PASS: "${TEMPTOP_PASS}"
      INFLUXDB_ADDRESS: "${INFLUXDB_ADDRESS}"
      INFLUXDB_USER: "${INFLUXDB_USER}"
      INFLUXDB_PASSWORD: "${INFLUXDB_PASSWORD}"
      INFLUXDB_DATABASE: "${INFLUXDB_DATABASE}"

  speedtest:
    build: ./speedtest
    image: jwright/speedtest
    container_name: speedtest
    depends_on:
      - influxdb
    restart: always
    environment:
      INFLUXDB_ADDRESS: "${INFLUXDB_ADDRESS}"
      INFLUXDB_USER: "${INFLUXDB_USER}"
      INFLUXDB_PASSWORD: "${INFLUXDB_PASSWORD}"
      INFLUXDB_DATABASE: "${INFLUXDB_DATABASE}"
